#!/bin/sh

ARCHIVEID=`uname -n`
WHO=`whoami`
DATE=`date +%c`
TARDATE=`date +%d%b%Y_%Hh%M`
TARDIR=$1
TARNAME=$1-$TARDATE-$WHO.tar
TARGZ=$TARNAME.gz

FILES=`find $TARDIR -type f -not -path "*/exec/*" -not -path "*CVS*" -iregex ".*[\.]?[^o]" -iregex "[^%#~]*" -not -path "*cscope*" -not -path "*core.*" -print`
echo Making archive: $TARGZ
echo "Archive made by $WHO on $ARCHIVEID, $DATE " > $TARDIR/archiveid;
tar cvf $TARNAME $FILES $TARDIR/archiveid
gzip -f $TARNAME
echo Done: $TARGZ.
