include $(DEVBASE)/make/Makeparams

XINC = tsp_prjcfg.h tsp_abs_types.h tsp_const_def.h tsp_simple_trace.h tsp_sys_headers.h \
       tsp_glu.h

build:: export_include

destroy::
	$(MAKE) remove_include

include $(DEVBASE)/make/Makerules
