#
# Generated by the configure script for:
# @PACKAGE_NAME@ version @PACKAGE_VERSION@

doxygen_input = tsp
static_pages = footer/footer.html header/header.html

htmldir = $(DEVBASE)/doc/html
rtfdir = $(DEVBASE)/doc/rtf
pdfdir = $(DEVBASE)/doc/pdf

all::
	@echo "------TSP--Documentation Generation BEGIN----------"; \
	mkdir -p $(htmldir); \
	mkdir -p $(rtfdir); \
	mkdir -p $(pdfdir); \
	doxygen tsp; \
	cp tsp.css $(htmldir); \
	cp -r header $(htmldir); \
	cp -r footer $(htmldir); \
	cp -r images $(htmldir); \
	echo "-------TSP--Documentation Generation END------------";

clean:
	$(RM) -rf $(htmldir)
	$(RM) -rf $(rtfdir)
	$(RM) -rf $(pdfdir)

