/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_PORT_RPC_H_RPCGEN
#define _TEST_PORT_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum TSP_port_enum {
	TSP_port_e0 = 0,
	TSP_port_e1 = 1,
	TSP_port_e2 = 2,
	TSP_port_e3 = 3,
	TSP_port_e4 = 4,
};
typedef enum TSP_port_enum TSP_port_enum;

struct TSP_port_struct {
	int i;
	double a;
	char *status_str;
};
typedef struct TSP_port_struct TSP_port_struct;

#define TSP_PORT 77
#define TSP_PORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_next 1
extern  TSP_port_enum * get_next_1(TSP_port_enum *, CLIENT *);
extern  TSP_port_enum * get_next_1_svc(TSP_port_enum *, struct svc_req *);
#define get 2
extern  TSP_port_struct * get_1(void *, CLIENT *);
extern  TSP_port_struct * get_1_svc(void *, struct svc_req *);
#define set 3
extern  int * set_1(TSP_port_struct *, CLIENT *);
extern  int * set_1_svc(TSP_port_struct *, struct svc_req *);
extern int tsp_port_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_next 1
extern  TSP_port_enum * get_next_1();
extern  TSP_port_enum * get_next_1_svc();
#define get 2
extern  TSP_port_struct * get_1();
extern  TSP_port_struct * get_1_svc();
#define set 3
extern  int * set_1();
extern  int * set_1_svc();
extern int tsp_port_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_TSP_port_enum (XDR *, TSP_port_enum*);
extern  bool_t xdr_TSP_port_struct (XDR *, TSP_port_struct*);

#else /* K&R C */
extern bool_t xdr_TSP_port_enum ();
extern bool_t xdr_TSP_port_struct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_PORT_RPC_H_RPCGEN */
