/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test_port_rpc.h"

typedef int int32_t;
bool_t
xdr_TSP_port_enum (XDR *xdrs, TSP_port_enum *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TSP_port_struct (XDR *xdrs, TSP_port_struct *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->status_str, ~0))
		 return FALSE;
	return TRUE;
}
