/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "test_port_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

TSP_port_enum *
get_next_1(TSP_port_enum *argp, CLIENT *clnt)
{
	static TSP_port_enum clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_next,
		(xdrproc_t) xdr_TSP_port_enum, (caddr_t) argp,
		(xdrproc_t) xdr_TSP_port_enum, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

TSP_port_struct *
get_1(void *argp, CLIENT *clnt)
{
	static TSP_port_struct clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_TSP_port_struct, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
set_1(TSP_port_struct *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, set,
		(xdrproc_t) xdr_TSP_port_struct, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
