/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test_port_rpc.h"

TSP_port_enum *
get_next_1_svc(TSP_port_enum *argp, struct svc_req *rqstp)
{
	static TSP_port_enum  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TSP_port_struct *
get_1_svc(void *argp, struct svc_req *rqstp)
{
	static TSP_port_struct  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
set_1_svc(TSP_port_struct *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
