/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test_port_rpc.h"
#include <stdio.h>
#include <stdlib.h>
#ifndef WIN32
#include <rpc/pmap_clnt.h>
#include <sys/socket.h>
#include <netinet/in.h>
#else
#include <winsock2.h>
#include <rpc/pmap_cln.h>
#endif
#include <string.h>
#include <memory.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
tsp_port_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		TSP_port_enum get_next_1_arg;
		TSP_port_struct set_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_next:
		_xdr_argument = (xdrproc_t) xdr_TSP_port_enum;
		_xdr_result = (xdrproc_t) xdr_TSP_port_enum;
		local = (char *(*)(char *, struct svc_req *)) get_next_1_svc;
		break;

	case get:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_TSP_port_struct;
		local = (char *(*)(char *, struct svc_req *)) get_1_svc;
		break;

	case set:
		_xdr_argument = (xdrproc_t) xdr_TSP_port_struct;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) set_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TSP_PORT, TSP_PORT_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TSP_PORT, TSP_PORT_VERS, tsp_port_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TSP_PORT, TSP_PORT_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TSP_PORT, TSP_PORT_VERS, tsp_port_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TSP_PORT, TSP_PORT_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
