#!/bin/tcsh

if ( ! $?STRACE_DEBUG ) then 
	setenv STRACE_DEBUG 3
endif
echo "Using STRACE_DEBUG= $STRACE_DEBUG"


alias myxterm "xterm -fn fixed -fg yellow -bg black  -geometry 40x10 -T "
alias myxterm2 "xterm -fn fixed -fg green -bg black -T "Serveur" -geometry 120x20"



cd $DEVBASE/exec/DEV/bin.provider
myxterm2 -e ./serveur1 0  &
sleep 1

cd $DEVBASE/exec/DEV/bin.consumer

#-----------------------------------------------------------
set PERIOD=1
myxterm "TSP Client. Period=$PERIOD"  -e ./client1 $1 $PERIOD &

#-----------------------------------------------------------
set PERIOD=10
myxterm "TSP Client. Period=$PERIOD"  -e ./client1 $1 $PERIOD &
myxterm "TSP Client. Period=$PERIOD"  -e ./client1 $1 $PERIOD &
myxterm "TSP Client. Period=$PERIOD"  -e ./client1 $1 $PERIOD &

#-----------------------------------------------------------
set PERIOD=100
myxterm "TSP Client. Period=$PERIOD"  -e ./client1 $1 $PERIOD &
myxterm "TSP Client. Period=$PERIOD"  -e ./client1 $1 $PERIOD &
myxterm "TSP Client. Period=$PERIOD"  -e ./client1 $1 $PERIOD &










