#Just simple makefile for building in all subdirs
include $(DEVBASE)/make/Makeparams

SUBDIRS = \
	stdout_callback \
	stdout \
	test_group \
	res_writer \
	tutorial \
	gdisp \
	gdisp+ \
	jstdout 

include $(DEVBASE)/make/Makesubdirs


