MESSAGE(STATUS "Looking for gtk-config...")
FIND_PROGRAM(GTK_CONFIG_PROGRAM 
  NAMES gtk-config 
  PATHS /usr/local/bin /usr/bin
  DOC "The gtk+1.2 configuration tool")
IF (GTK_CONFIG_PROGRAM) 
  MESSAGE(STATUS "Looking for gtk-config - found : ${GTK_CONFIG_PROGRAM}")
  SET(GTK_FOUND "YES")
  EXECUTE_PROCESS(COMMAND ${GTK_CONFIG_PROGRAM} --libs
		  OUTPUT_VARIABLE GTK_LIBRARY
		  OUTPUT_STRIP_TRAILING_WHITESPACE)
  EXECUTE_PROCESS(COMMAND ${GTK_CONFIG_PROGRAM} --cflags
		  OUTPUT_VARIABLE GTK_CFLAGS
		  OUTPUT_STRIP_TRAILING_WHITESPACE)
  SET(GTK_DEVEL_PACKAGE gtk+-devel)  
ELSE (GTK_CONFIG_PROGRAM)
  MESSAGE(STATUS "Looking for gtk-config - NOT found") 
ENDIF (GTK_CONFIG_PROGRAM)
