#!/bin/csh

setenv STRACE_DEBUG 1

echo "Run provider with no file"
tsp_res_reader > /dev/null &
tsp_res_reader file.res > /dev/null &
sleep 1

echo "Run consumer of file.res"
tsp_res_writer -f out.res -u localhost

diff file.res out.res
set RES=$status

if ( "$RES" == "0") then
    echo "Test OK, both res are equal"
else
    echo "Test KO, res differ "
    exit 1
endif

\rm out.res

echo "--------------------------------"
echo "-------- END AUTOTEST ----------"
echo "--------------------------------"
exit 0










