#!/bin/csh

setenv STRACE_DEBUG 1

echo "Run provider with no file"
tsp_res_reader > /dev/null &
sleep 1

echo "Run consumer of file.res"
tsp_res_writer localhost 1  --tsp-stream-init-start file.res --tsp-stream-init-stop out.res f 1 

diff file.res out.res
set RES=$status

if ( "$RES" == "0") then
    echo "Test OK, both res are equal"
else
    echo "Test KO, res differ "
    exit 1
endif

\rm out.res

echo "--------------------------------"
echo "-------- END AUTOTEST ----------"
echo "--------------------------------"
exit 0










