#!/bin/tcsh

#get test number
set TESTNB=`echo $0 | perl -n -e  '~/([1-9][0-9]*)$/;print $1'`

set PROVIDER=tsp_stub_server
set CONSUMER=tsp_testgrp_client


echo "------------------------------------"
echo "---------- AUTOTEST $TESTNB ------------"
echo "------------------------------------"
echo " - Tests groups calculation "


setenv STRACE_DEBUG 2




$PROVIDER   > /dev/null &
sleep 1

#useful : will connect to servers 1,2,3 et talks to 1
$CONSUMER localhost 1

set RESULT=$?

#kill our army of dummies
custom_killall $PROVIDER
custom_killall $CONSUMER

if ( "$RESULT" == "0") then
    echo "TEST||++++ STAGE 002 : PASSED ++++"
    set RET=0
else
    echo "TEST||@@@@ STAGE 002 : FAILED @@@@"
    set RET=1
endif


echo "------------------------------------"
echo "-------- END AUTOTEST $TESTNB ----------"
echo "------------------------------------"
exit $RET










